/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ThreeLaneAmbushInterface extends Interface {
  getFunction(
    nameOrSignature: "getLastResult" | "lastResult" | "play"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GamePlayed"): EventFragment;

  encodeFunctionData(
    functionFragment: "getLastResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "play",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLastResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastResult", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "play", data: BytesLike): Result;
}

export namespace GamePlayedEvent {
  export type InputTuple = [player: AddressLike, result: BigNumberish];
  export type OutputTuple = [player: string, result: bigint];
  export interface OutputObject {
    player: string;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ThreeLaneAmbush extends BaseContract {
  connect(runner?: ContractRunner | null): ThreeLaneAmbush;
  waitForDeployment(): Promise<this>;

  interface: ThreeLaneAmbushInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLastResult: TypedContractMethod<[], [bigint], "view">;

  lastResult: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  play: TypedContractMethod<
    [
      playerLaneHash: BytesLike,
      playerPowerHash: BytesLike,
      playerLane: BigNumberish,
      playerPower: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLastResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastResult"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "play"
  ): TypedContractMethod<
    [
      playerLaneHash: BytesLike,
      playerPowerHash: BytesLike,
      playerLane: BigNumberish,
      playerPower: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "GamePlayed"
  ): TypedContractEvent<
    GamePlayedEvent.InputTuple,
    GamePlayedEvent.OutputTuple,
    GamePlayedEvent.OutputObject
  >;

  filters: {
    "GamePlayed(address,uint8)": TypedContractEvent<
      GamePlayedEvent.InputTuple,
      GamePlayedEvent.OutputTuple,
      GamePlayedEvent.OutputObject
    >;
    GamePlayed: TypedContractEvent<
      GamePlayedEvent.InputTuple,
      GamePlayedEvent.OutputTuple,
      GamePlayedEvent.OutputObject
    >;
  };
}
