/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  EthereumZamaFHEVMConfig,
  EthereumZamaFHEVMConfigInterface,
} from "../../../../fhevm/config/ZamaFHEVMConfig.sol/EthereumZamaFHEVMConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b5061011861003c604080516080810182525f80825260208201819052918101829052606081019190915290565b80517fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea60080546001600160a01b03199081166001600160a01b039384161790915560208301517fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6018054831691841691909117905560408301517fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6028054831691841691909117905560608301517fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6038054909216921691909117905550565b6015806101245f395ff3fe60806040525f80fdfea164736f6c6343000818000a";

type EthereumZamaFHEVMConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EthereumZamaFHEVMConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EthereumZamaFHEVMConfig__factory extends ContractFactory {
  constructor(...args: EthereumZamaFHEVMConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EthereumZamaFHEVMConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): EthereumZamaFHEVMConfig__factory {
    return super.connect(runner) as EthereumZamaFHEVMConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthereumZamaFHEVMConfigInterface {
    return new Interface(_abi) as EthereumZamaFHEVMConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EthereumZamaFHEVMConfig {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as EthereumZamaFHEVMConfig;
  }
}
