/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EthereumZamaFHEVMConfig__factory } from "./EthereumZamaFHEVMConfig__factory";
export { SepoliaZamaFHEVMConfig__factory } from "./SepoliaZamaFHEVMConfig__factory";
