/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IFHEVMExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cast"
      | "fheAdd"
      | "fheEq"
      | "fheGe"
      | "fheGt"
      | "fheIfThenElse"
      | "fheLe"
      | "fheLt"
      | "fheMul"
      | "fheSub"
      | "trivialEncrypt"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cast",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fheAdd",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheEq",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheGe",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheGt",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheIfThenElse",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheLe",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheLt",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheMul",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheSub",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trivialEncrypt",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "cast", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheAdd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheEq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheGe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheGt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fheIfThenElse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fheLe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheLt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheMul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheSub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "trivialEncrypt",
    data: BytesLike
  ): Result;
}

export interface IFHEVMExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): IFHEVMExecutor;
  waitForDeployment(): Promise<this>;

  interface: IFHEVMExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cast: TypedContractMethod<
    [ct: BytesLike, toType: BigNumberish],
    [string],
    "nonpayable"
  >;

  fheAdd: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  fheEq: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  fheGe: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  fheGt: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  fheIfThenElse: TypedContractMethod<
    [control: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;

  fheLe: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  fheLt: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  fheMul: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  fheSub: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  trivialEncrypt: TypedContractMethod<
    [ct: BigNumberish, toType: BigNumberish],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cast"
  ): TypedContractMethod<
    [ct: BytesLike, toType: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheAdd"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheEq"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheGe"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheGt"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheIfThenElse"
  ): TypedContractMethod<
    [control: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheLe"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheLt"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheMul"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheSub"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trivialEncrypt"
  ): TypedContractMethod<
    [ct: BigNumberish, toType: BigNumberish],
    [string],
    "nonpayable"
  >;

  filters: {};
}
