/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IFHEVMExecutorInterface extends Interface {
  getFunction(
    nameOrSignature: "fheEq" | "fheGt" | "fheIfThenElse"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "fheEq",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheGt",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheIfThenElse",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "fheEq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheGt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fheIfThenElse",
    data: BytesLike
  ): Result;
}

export interface IFHEVMExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): IFHEVMExecutor;
  waitForDeployment(): Promise<this>;

  interface: IFHEVMExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fheEq: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  fheGt: TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;

  fheIfThenElse: TypedContractMethod<
    [control: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fheEq"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheGt"
  ): TypedContractMethod<
    [lhs: BytesLike, rhs: BytesLike, scalarByte: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheIfThenElse"
  ): TypedContractMethod<
    [control: BytesLike, ifTrue: BytesLike, ifFalse: BytesLike],
    [string],
    "nonpayable"
  >;

  filters: {};
}
