/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ThreeLaneAmbushInterface extends Interface {
  getFunction(
    nameOrSignature: "owner" | "play" | "setComputerMove"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GamePlayed"): EventFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "play",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setComputerMove",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "play", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setComputerMove",
    data: BytesLike
  ): Result;
}

export namespace GamePlayedEvent {
  export type InputTuple = [player: AddressLike, result: BytesLike];
  export type OutputTuple = [player: string, result: string];
  export interface OutputObject {
    player: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ThreeLaneAmbush extends BaseContract {
  connect(runner?: ContractRunner | null): ThreeLaneAmbush;
  waitForDeployment(): Promise<this>;

  interface: ThreeLaneAmbushInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  owner: TypedContractMethod<[], [string], "view">;

  play: TypedContractMethod<
    [playerEncryptedLane: BytesLike, playerEncryptedPower: BytesLike],
    [void],
    "nonpayable"
  >;

  setComputerMove: TypedContractMethod<
    [encryptedLane: BytesLike, encryptedPower: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "play"
  ): TypedContractMethod<
    [playerEncryptedLane: BytesLike, playerEncryptedPower: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setComputerMove"
  ): TypedContractMethod<
    [encryptedLane: BytesLike, encryptedPower: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GamePlayed"
  ): TypedContractEvent<
    GamePlayedEvent.InputTuple,
    GamePlayedEvent.OutputTuple,
    GamePlayedEvent.OutputObject
  >;

  filters: {
    "GamePlayed(address,bytes)": TypedContractEvent<
      GamePlayedEvent.InputTuple,
      GamePlayedEvent.OutputTuple,
      GamePlayedEvent.OutputObject
    >;
    GamePlayed: TypedContractEvent<
      GamePlayedEvent.InputTuple,
      GamePlayedEvent.OutputTuple,
      GamePlayedEvent.OutputObject
    >;
  };
}
