/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ThreeLaneAmbushFHEInterface extends Interface {
  getFunction(
    nameOrSignature: "getEncryptedResult" | "play" | "protocolId"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GameResultReady"): EventFragment;

  encodeFunctionData(
    functionFragment: "getEncryptedResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "play",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getEncryptedResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "play", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace GameResultReadyEvent {
  export type InputTuple = [player: AddressLike];
  export type OutputTuple = [player: string];
  export interface OutputObject {
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ThreeLaneAmbushFHE extends BaseContract {
  connect(runner?: ContractRunner | null): ThreeLaneAmbushFHE;
  waitForDeployment(): Promise<this>;

  interface: ThreeLaneAmbushFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEncryptedResult: TypedContractMethod<
    [player: AddressLike],
    [string],
    "view"
  >;

  play: TypedContractMethod<
    [
      laneHandle: BytesLike,
      laneProof: BytesLike,
      powerHandle: BytesLike,
      powerProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEncryptedResult"
  ): TypedContractMethod<[player: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "play"
  ): TypedContractMethod<
    [
      laneHandle: BytesLike,
      laneProof: BytesLike,
      powerHandle: BytesLike,
      powerProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "GameResultReady"
  ): TypedContractEvent<
    GameResultReadyEvent.InputTuple,
    GameResultReadyEvent.OutputTuple,
    GameResultReadyEvent.OutputObject
  >;

  filters: {
    "GameResultReady(address)": TypedContractEvent<
      GameResultReadyEvent.InputTuple,
      GameResultReadyEvent.OutputTuple,
      GameResultReadyEvent.OutputObject
    >;
    GameResultReady: TypedContractEvent<
      GameResultReadyEvent.InputTuple,
      GameResultReadyEvent.OutputTuple,
      GameResultReadyEvent.OutputObject
    >;
  };
}
