/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFHEVMExecutor,
  IFHEVMExecutorInterface,
} from "../../../contracts/ThreeLaneAmbush.sol/IFHEVMExecutor";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
      {
        internalType: "bytes1",
        name: "scalarByte",
        type: "bytes1",
      },
    ],
    name: "fheEq",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "lhs",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "rhs",
        type: "bytes32",
      },
      {
        internalType: "bytes1",
        name: "scalarByte",
        type: "bytes1",
      },
    ],
    name: "fheGt",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "control",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "ifTrue",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "ifFalse",
        type: "bytes32",
      },
    ],
    name: "fheIfThenElse",
    outputs: [
      {
        internalType: "bytes32",
        name: "result",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFHEVMExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): IFHEVMExecutorInterface {
    return new Interface(_abi) as IFHEVMExecutorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFHEVMExecutor {
    return new Contract(address, _abi, runner) as unknown as IFHEVMExecutor;
  }
}
