/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthereumZamaFHEVMConfig } from "./EthereumZamaFHEVMConfig";
export type { SepoliaZamaFHEVMConfig } from "./SepoliaZamaFHEVMConfig";
